### ISSUE TITLE
ZAP TOKEN

### ISSUE THREAD

**Issue by darrylhansen** [Uniswap/default-token-list#127]
- [X ] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X ] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [ X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x6781a0f84c7e9e846dcb84a9a5bd49333067b104
Token Name (from contract): ZAP TOKEN
Token Decimals (from contract): 18
Token Symbol (from contract): ZAP
Uniswap V2 Pair Address of Token: 0xde2e46992bD4F86471B52f21Dac2d7c9F6deAc26

Link to the official homepage of token: https://www.zap.org
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/zap/

**Comment by adammmanka** [comment]
@darrylhansen why was this closed? Is it listed and if so can you provide a link?

**Comment by darrylhansen** [comment]
Hey @adammanka, this token request is still open.  The initial request I put in the wrong spot (under interface issues instead of Default Token List), so I closed that one and referenced this request in the comments 👍
