### ISSUE TITLE
Add MLN Token

### ISSUE THREAD

**Issue by martinkrung** [Uniswap/default-token-list#205]
Token Address: 0xec67005c4e498ec7f55e092bd1d35cbc47c91892
Token Name (from contract): Melon Token 
Token Decimals (from contract): 18
Token Symbol (from contract):  MLN
Uniswap Exchange Address of Token: 0xa931f4eb165ac307fd7431b5ec6eadde53e14b0c

Link to the official homepage of the token: https://melonport.com

**Comment by Ivshti** [comment]
> @fabtho yeah Uniswap icons are pulled from that trust repo

is this still accurate?
