### ISSUE TITLE
Please Add HUSD (stablecoin) to default token list

### ISSUE THREAD

**Issue by ycclaude** [Uniswap/default-token-list#219]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xdf574c24545e5ffecb9a659c229253d4111d87e1
Token Name (from contract): HUSD
Token Decimals (from contract): 8
Token Symbol (from contract): HUSD
Uniswap V2 Pair Address of Token: https://uniswap.info/pair/0x8749068c5b45Fdaa369319E5DAa1e5f332419c6D

Link to the official homepage of token: https://www.stcoins.com/

Link to CoinMarketCap or CoinGecko page of token: 
https://coinmarketcap.com/currencies/husd/
https://www.coingecko.com/en/coins/husd

**Comment by NoahZinsmeister** [comment]
hi @ycclaude , please open a PR for this token

**Comment by ycclaude** [comment]
> hi @ycclaude , please open a PR for this token

Thank you. I already add the PR. Please help to check.
