### ISSUE TITLE
Adding NKN to Uniswap

### ISSUE THREAD

**Issue by zbruceli** [Uniswap/default-token-list#221]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x5cf04716ba20127f1e2297addcf4b5035000c9eb
Token Name (from contract): NKN
Token Decimals (from contract): 18
Token Symbol (from contract): NKN
Uniswap V2 NKN/ETH Pair Address of Token: [0x1740aa56eb4e333bacd317dacd0cf28043d8e8a1](https://uniswap.info/pair/0x1740aa56eb4e333bacd317dacd0cf28043d8e8a1)
Uniswap V2 NKN/USDT Pair Address of Token: [0x7f75f0aed3c4158b91ad3641afa6e8d035311862](https://uniswap.info/pair/0x7f75f0aed3c4158b91ad3641afa6e8d035311862)

Link to the official homepage of token: https://nkn.org
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/nkn/

**Comment by kennethffx2** [comment]
^___^

**Comment by zbruceli** [comment]
Completed via coingecko token list.
